name: 'integration_tests'
version: '1.0.0'
config-version: 2

profile: 'default'



#vars:
#  tuva_database: dev_user
#  tuva_schema_prefix: test
# Set the input database and schema:
#  claims_preprocessing_input_database: dev_suer
#  claims_preprocessing_input_schema: claims_common
#  claims_preprocessing_schema: frbtest3_core
#  terminology_database: dev_
#  terminology_schema: terminology
#  tuva_packages_enabled: false
#  claims_preprocessing_enabled: true

#  pharmacy_claim_exists: false

dispatch:
  - macro_namespace: dbt
    search_order: [ 'claims_preprocessing', 'dbt']



model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  integration_tests:
    +materialized: ephemeral
    +database: dev_user